realman-rm75-6f-v:
  container_name: embodied-realman-rm75-6f-v
  image: __IMAGE__
  privileged: true
  volumes:
    - /dev:/dev
    - /opt/realman/rm_ws:/rm_ws:ro
  environment:
    - ROS_DOMAIN_ID=42
    - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    - ROS_LOCALHOST_ONLY=0
    - PYTHONUNBUFFERED=1
    - RCUTILS_COLORIZED_OUTPUT=0
  logging:
    driver: local
    options:
      max-size: "10m"
      max-file: "3"
  restart: unless-stopped
