"""Same-origin installation and pairing flow served by the PICO Driver."""

PAGE = r"""<!doctype html><html lang="zh"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>连接机器人 · PhanthyMotus</title>
<style>body{font:18px system-ui;max-width:680px;margin:24px auto;padding:20px;line-height:1.7;color:#26221f}section{border:1px solid #ddd;border-radius:14px;padding:20px;margin:20px 0}button,a{font:inherit;touch-action:manipulation}button,.primary{display:inline-block;background:#b65d32;color:white;border:0;border-radius:8px;padding:12px 20px;text-decoration:none;cursor:pointer}button:disabled{opacity:.5}small{color:#666}details{margin-top:24px}details button{background:#eee;color:#333;margin:8px 0}#error{color:#a32616}[hidden]{display:none!important}#fingerprint{overflow-wrap:anywhere}</style>
<h1>连接这台机器人</h1><p>请在 PICO 浏览器打开本页。无需密码，连接后不会自动运动。</p>
<section><h2>1 · 安装 App</h2><a class="primary" href="/onboarding/apk">下载 PICO App</a><p id="package">正在检查安装包…</p><small>下载后确认安装，再返回本页。已经安装可直接进行下一步。</small></section>
<section><h2>2 · 打开并连接</h2><p id="status" role="status">正在读取连接状态…</p><button id="prepare">连接这台机器人</button><a id="connect" class="primary" hidden>打开 App 并连接</a><p><small>如果在电脑上查看，请把当前网址复制到 PICO 浏览器。已配对的 App 再次打开会自动重连。</small></p>
<div id="pending" hidden><p>发现待配对设备，请核对头显中显示的指纹：</p><strong id="fingerprint"></strong><p><button data-action="approve">指纹一致，允许连接</button> <button data-action="reject">不是我的设备</button></p></div></section>
<p id="error" role="alert"></p>
<details><summary>其他连接方式与设备管理</summary><p>App 的“刷新局域网机器人”通过同一局域网的服务广播发现机器人，不扫描 IP。访客 Wi-Fi、组播隔离或跨网段时可能找不到；优先使用上方连接入口。</p><button data-action="open">允许 App 手动发现配对（120 秒）</button><p><small>随后在 App 选择机器人，按提示核对指纹。本页会自动显示配对请求。</small></p><button data-action="revoke_headset">忘记已配对的 PICO</button><p><small>只有更换头显或重新配对时才需要忘记设备。</small></p></details>
<script>
const el=id=>document.getElementById(id);let pending=null,busy=false;
const errors={pairing_window_closed:'配对窗口已关闭，请重新允许手动配对。',revoke_existing_headset_first:'已有配对设备；请直接打开已配对的 App。更换头显时，在设备管理中忘记旧设备。',invitation_expired:'连接邀请已过期，请重新点击连接。'};
async function call(action,values={}){const r=await fetch('/manage/'+action,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});const v=await r.json();if(!r.ok)throw Error(errors[v.error]||v.error||'请求失败，请重试');return v;}
function show(v){if(v.pairing){pending=v.pairing.pending;if(!v.pairing.invitation)el('connect').hidden=true;el('pending').hidden=!pending;el('fingerprint').textContent=pending?pending.fingerprint:'';}if(v.capture){el('status').textContent=v.capture.connected?'PICO 已连接。在 App 进入透视采集，按住双握把开始遥操。':v.capture.paired_devices?'已配对，请打开 PICO App 自动重连。':'尚未配对，点击下方按钮，App 将自动填好这台机器人的地址。';el('prepare').hidden=!!v.capture.paired_devices||!el('connect').hidden;if(v.capture.paired_devices)el('connect').hidden=true;}}
async function refresh(){if(busy)return;try{show(await call('status'));}catch(e){el('error').textContent='暂时无法读取状态：'+e.message;}}
el('prepare').onclick=async()=>{busy=true;el('prepare').disabled=true;el('error').textContent='';try{const v=await call('invite');el('connect').href=v.deep_link;el('connect').hidden=false;el('prepare').hidden=true;el('status').textContent='地址已准备好，点击“打开 App 并连接”，无需手动填写。';}catch(e){el('error').textContent=e.message;}finally{busy=false;el('prepare').disabled=false;}};
for(const b of document.querySelectorAll('[data-action]'))b.onclick=async()=>{busy=true;b.disabled=true;el('error').textContent='';try{const a=b.dataset.action;let data={};if(a==='approve'||a==='reject'){if(!pending)throw Error('当前没有待配对设备');data={request_id:pending.request_id,fingerprint:pending.fingerprint};}if(a==='revoke_headset'&&!confirm('忘记设备后需要重新连接，继续？'))return;show(await call(a,data));if(a==='revoke_headset')el('connect').hidden=true;}catch(e){el('error').textContent=e.message;}finally{busy=false;b.disabled=false;await refresh();}};
refresh();setInterval(refresh,2000);
fetch('/onboarding/package').then(r=>r.json()).then(v=>{el('package').textContent=v.available?'版本 '+v.version:'安装包尚未就绪，请联系部署人员。';}).catch(()=>{el('package').textContent='暂时无法读取安装包信息，请刷新页面。';});
</script></html>"""
