ubtrobot-u1-pro:
  image: __IMAGE__
  container_name: embodied-ubtrobot-u1-pro
  network_mode: host
  ipc: host
  pid: host
  privileged: true
  environment:
    - ROS_DOMAIN_ID=42
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    - ROS_LOCALHOST_ONLY=1
    - RCUTILS_COLORIZED_OUTPUT=0
    - PYTHONUNBUFFERED=1
  restart: unless-stopped
