cmake_minimum_required(VERSION 3.8)
project(bodyctrl_msgs)

find_package(ament_cmake REQUIRED)
find_package(rosidl_default_generators REQUIRED)
find_package(std_msgs REQUIRED)
find_package(geometry_msgs REQUIRED)

rosidl_generate_interfaces(${PROJECT_NAME}
  "msg/Alarm.msg"
  "msg/AlarmArray.msg"
  "msg/CmdMotorCtrl.msg"
  "msg/CmdSetMotorCurTor.msg"
  "msg/CmdSetMotorDistance.msg"
  "msg/CmdSetMotorPosition.msg"
  "msg/CmdSetMotorSpeed.msg"
  "msg/CmdSetParam.msg"
  "msg/CmdSetTsHandCtrl.msg"
  "msg/CmdSetTsHandPosition.msg"
  "msg/CmdSetWaistMotorPos.msg"
  "msg/EtherCatSlaveRestart.msg"
  "msg/Euler.msg"
  "msg/Exception.msg"
  "msg/ExceptionArray.msg"
  "msg/Imu.msg"
  "msg/LightCtrl.msg"
  "msg/MotorCtrl.msg"
  "msg/MotorName.msg"
  "msg/MotorStatus.msg"
  "msg/MotorStatus1.msg"
  "msg/MotorStatusMsg.msg"
  "msg/MotorStatusMsg1.msg"
  "msg/MotorStatusMsg2.msg"
  "msg/MotorStatusMsgPlate.msg"
  "msg/NodeState.msg"
  "msg/PowerBatteryStatus.msg"
  "msg/PowerBoardCtrl.msg"
  "msg/PowerBoardKeyStatus.msg"
  "msg/PowerLightCtrl.msg"
  "msg/PowerStatus.msg"
  "msg/SbusData.msg"
  "msg/SetMotorCurTor.msg"
  "msg/SetMotorDistance.msg"
  "msg/SetMotorPosition.msg"
  "msg/SetMotorSpeed.msg"
  "msg/SetParam.msg"
  "msg/SetTsHandCtrl.msg"
  "msg/SetTsHandCtrlItem.msg"
  "msg/SetTsHandPosition.msg"
  "msg/Sri.msg"
  "msg/SriName.msg"
  "msg/TsHandName.msg"
  "msg/TsHandStatus.msg"
  "msg/TsHandStatusMsg.msg"
  "msg/WaistMotorStatus.msg"
  "srv/GetAngleAct.srv"
  "srv/GetError.srv"
  "srv/GetForceAct.srv"
  "srv/GetStatus.srv"
  "srv/JointSetZero.srv"
  "srv/MotorInit.srv"
  "srv/MotorResetPosition.srv"
  "srv/MotorStart.srv"
  "srv/MotorStop.srv"
  "srv/Movement.srv"
  "srv/PlanEefLine.srv"
  "srv/PlanEefRelLine.srv"
  "srv/PlanJointTraj.srv"
  "srv/ResetMotorZeroOffset.srv"
  "srv/SetAngle.srv"
  "srv/SetAngleFlexible.srv"
  "srv/SetClearError.srv"
  "srv/SetForce.srv"
  "srv/SetGestureForceCalibration.srv"
  "srv/SetMotorZeroOffset.srv"
  "srv/SetSpeed.srv"
  "srv/VersionUpgrade.srv"
  "srv/XSensImuInit.srv"
  DEPENDENCIES std_msgs geometry_msgs
)

ament_package()
