mcp_port: 15716
ros_namespace: ""
name: "DEEPRobotics Lynx S10"
ros:
  robot_domain_id: 0
  core_domain_id: 42
  robot_interface: "eth0"
topics:
  command: "/lynx_s10/driver/command"
  state: "/lynx_s10/driver/state"
  ack: "/lynx_s10/driver/ack"
  cmd_vel: "/cmd_vel"
  goal_pose: "/goal_pose"
  joint_states: "/joint_states"
  imu: "/imu/data"
  odometry: "/odom"
  battery: "/battery_state"
  camera: "/camera/color/image_raw"
  depth: "/camera/depth/image_raw"
  lidar: "/lidar/points"
