agibot-x2:
  image: __IMAGE__
  container_name: embodied-agibot-x2
  network_mode: host
  ipc: host
  pid: host
  privileged: true
  volumes:
    - /dev:/dev
    - /opt/phanthy-motus/data:/opt/phanthy-motus/data
  environment:
    - ROS_DOMAIN_ID=42
    - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    - NETWORK_INTERFACE=develop0
    - FASTRTPS_DEFAULT_PROFILES_FILE=/work/agibot/AimDK_X2/resource/fastdds_develop0.xml
    - PYTHONUNBUFFERED=1
  logging:
    driver: local
    options:
      max-size: "10m"
      max-file: "3"
  restart: unless-stopped
