"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: sensor_msgs.msg.dds_
  IDL file: Imu_.idl

"""

from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Imu_(idl.IdlStruct, typename="sensor_msgs.msg.dds_.Imu_"):
    header: 'unitree_sdk2py.idl.std_msgs.msg.dds_.Header_'
    orientation: 'unitree_sdk2py.idl.geometry_msgs.msg.dds_.Quaternion_'
    orientation_covariance: types.array[types.float64, 9]
    angular_velocity: 'unitree_sdk2py.idl.geometry_msgs.msg.dds_.Vector3_'
    angular_velocity_covariance: types.array[types.float64, 9]
    linear_acceleration: 'unitree_sdk2py.idl.geometry_msgs.msg.dds_.Vector3_'
    linear_acceleration_covariance: types.array[types.float64, 9]
